server:
  port: 8081
spring:
  profiles: default
  application:
    name: Oauth2 JWK Resource server
security:
  oauth2:
    resource:
      jwk:
        key-set-uri: http://localhost:8080/.well-known/jwks.json
